import { randomUUID } from 'node:crypto';
import { writeFile, mkdir } from 'node:fs/promises';
import { join, basename, extname } from 'node:path';
import type { GeneratedTest, SourceSymbol, EdgeCase } from '../types.js';

// ---------------------------------------------------------------------------
// Test generator — emits Vitest test files from symbol + edge-case data.
// ---------------------------------------------------------------------------

export async function generateTests(
  symbols: SourceSymbol[],
  edgeCases: EdgeCase[],
  outputDir: string,
  kind: 'unit' | 'integration' | 'both' = 'both',
): Promise<GeneratedTest[]> {
  await mkdir(outputDir, { recursive: true });

  const results: GeneratedTest[] = [];

  if (kind === 'unit' || kind === 'both') {
    const unitTests = await generateUnitTests(symbols, edgeCases, outputDir);
    results.push(...unitTests);
  }

  if (kind === 'integration' || kind === 'both') {
    const intTests = await generateIntegrationTests(symbols, outputDir);
    results.push(...intTests);
  }

  return results;
}

// ---------------------------------------------------------------------------
// Unit test generation
// ---------------------------------------------------------------------------

async function generateUnitTests(
  symbols: SourceSymbol[],
  edgeCases: EdgeCase[],
  outputDir: string,
): Promise<GeneratedTest[]> {
  // Group symbols by source file
  const byFile = new Map<string, SourceSymbol[]>();
  for (const sym of symbols) {
    const group = byFile.get(sym.filePath) ?? [];
    group.push(sym);
    byFile.set(sym.filePath, group);
  }

  const tests: GeneratedTest[] = [];

  for (const [filePath, fileSymbols] of byFile) {
    const fileBase = basename(filePath, extname(filePath));
    const testFileName = `${fileBase}.unit.test.ts`;
    const testFilePath = join(outputDir, testFileName);
    const source = renderUnitTestFile(filePath, fileSymbols, edgeCases);

    await writeFile(testFilePath, source, 'utf8');
    tests.push({
      id: randomUUID(),
      targetFile: filePath,
      testFilePath,
      kind: 'unit',
      source,
      createdAt: new Date(),
    });
  }

  return tests;
}

function renderUnitTestFile(
  filePath: string,
  symbols: SourceSymbol[],
  edgeCases: EdgeCase[],
): string {
  const relativeImport = filePath.replace(/\\/g, '/');
  const lines: string[] = [
    `// Auto-generated by TestForge — do not edit manually.`,
    `import { describe, it, expect, vi } from 'vitest';`,
    `// TODO: update this import path to match your project layout`,
    `// import { ... } from '${relativeImport}';`,
    ``,
  ];

  for (const sym of symbols) {
    if (sym.kind === 'class') continue; // classes get their own blocks
    const symCases = edgeCases.filter((ec) => ec.symbolName === sym.name);

    lines.push(`describe('${sym.name}', () => {`);
    lines.push(`  it('should be defined', () => {`);
    lines.push(`    // TODO: import ${sym.name} and assert it is defined`);
    lines.push(`    expect(true).toBe(true);`);
    lines.push(`  });`);
    lines.push(``);
    lines.push(`  it('should return expected result for valid input', () => {`);
    lines.push(`    // TODO: call ${sym.name}(${sym.params.map((p) => p.name).join(', ')}) with valid args`);
    lines.push(`    expect(true).toBe(true);`);
    lines.push(`  });`);

    for (const ec of symCases) {
      lines.push(``);
      lines.push(`  it('edge case — ${ec.description.replace(/'/g, "\\'")}', () => {`);
      lines.push(`    // Category: ${ec.category}`);
      lines.push(`    // Input suggestion: ${ec.inputSuggestion}`);
      lines.push(`    // Expected: ${ec.expectedBehaviour}`);
      if (ec.category === 'async-error') {
        lines.push(`    await expect(async () => { /* call ${sym.name} */ }).rejects.toThrow();`);
      } else if (ec.category === 'nullish') {
        lines.push(`    // TODO: call with ${ec.inputSuggestion} and assert the error`);
        lines.push(`    expect(true).toBe(true);`);
      } else {
        lines.push(`    expect(true).toBe(true);`);
      }
      lines.push(`  });`);
    }

    lines.push(`});`);
    lines.push(``);
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Integration test generation (Express route stubs)
// ---------------------------------------------------------------------------

async function generateIntegrationTests(
  symbols: SourceSymbol[],
  outputDir: string,
): Promise<GeneratedTest[]> {
  const testFileName = `api.integration.test.ts`;
  const testFilePath = join(outputDir, testFileName);
  const source = renderIntegrationTestFile(symbols);

  await writeFile(testFilePath, source, 'utf8');
  return [
    {
      id: randomUUID(),
      targetFile: '(api)',
      testFilePath,
      kind: 'integration',
      source,
      createdAt: new Date(),
    },
  ];
}

function renderIntegrationTestFile(symbols: SourceSymbol[]): string {
  const lines: string[] = [
    `// Auto-generated by TestForge — do not edit manually.`,
    `import { describe, it, expect } from 'vitest';`,
    `import request from 'supertest';`,
    `import { createApp } from '../src/app.js';`,
    ``,
    `const app = createApp();`,
    ``,
    `describe('TestForge API', () => {`,
    `  it('GET /health — returns 200 and ok status', async () => {`,
    `    const res = await request(app).get('/health');`,
    `    expect(res.status).toBe(200);`,
    `    expect(res.body.status).toBe('ok');`,
    `  });`,
    ``,
    `  it('POST /api/analyse — validates request body', async () => {`,
    `    const res = await request(app).post('/api/analyse').send({});`,
    `    expect(res.status).toBe(400);`,
    `  });`,
    ``,
    `  it('POST /api/generate — validates request body', async () => {`,
    `    const res = await request(app).post('/api/generate').send({});`,
    `    expect(res.status).toBe(400);`,
    `  });`,
    ``,
    `  it('GET /api/report/unknown-id — returns 404', async () => {`,
    `    const res = await request(app).get('/api/report/unknown-id');`,
    `    expect(res.status).toBe(404);`,
    `  });`,
    ``,
  ];

  if (symbols.length > 0) {
    lines.push(`  // Symbol-derived stubs (${symbols.length} symbol(s) found):`);
    for (const sym of symbols.slice(0, 5)) {
      lines.push(`  // it('${sym.name} — ...', async () => { /* TODO */ });`);
    }
    lines.push(``);
  }

  lines.push(`});`);
  return lines.join('\n');
}
