# app.py
import sys
import types
import io
import pytest
import streamlit as st
from core_engine import run_bbob_analysis

# --- PAGE LAYOUT CONFIG ---
st.set_page_config(page_title="IBM Bob 2.0 PR Guardian & TestCraft", layout="wide")
st.title("🧪 TestCraft AI — Powered by IBM Bob 2.0")
st.caption("Automated Multi-Agent Test Generation, Security AST Auditing, and Zero-I/O In-Memory Test Execution")


@st.cache_data(show_spinner=False)
def parse_uploaded_file(file_bytes: bytes) -> str:
    """Cached file decoder to prevent reading bytes on re-renders."""
    return file_bytes.decode("utf-8", errors="ignore")


@st.fragment
def render_results_section(results: dict, source_code: str):
    """Scoped UI Fragment: Prevents full app script re-runs during user tab clicks."""
    if "error" in results:
        st.error(results["error"])
        return

    # --- EXECUTIVE SCORECARD METRICS ---
    st.subheader("📊 Execution Scorecard & Analysis")
    m1, m2, m3, m4 = st.columns(4)

    comp = results.get("complexity_analysis", {})
    tests = results.get("generated_tests", [])
    sec_issues = results.get("security_issues", [])
    perf_warns = results.get("performance_warnings", [])
    total_tests = len(tests)

    m1.metric("Detected Complexity", comp.get("time_complexity", "O(N)"))
    m2.metric("Total Test Cases Synthesized", total_tests)
    m3.metric("Security Alerts", len(sec_issues), delta_color="inverse")
    m4.metric("Performance Warnings", len(perf_warns), delta_color="inverse")

    st.divider()

    # --- SECURITY & PERFORMANCE AUDITS ---
    if sec_issues or perf_warns:
        st.subheader("🚨 Security & Performance Audits")
        for issue in sec_issues:
            st.error(f"🔴 {issue}")
        for warn in perf_warns:
            st.warning(f"🟡 {warn}")
        st.divider()

    # --- GENERATED TEST SUITE & IN-MEMORY RUNNER ---
    st.subheader("🛡️ Generated Test Suite & Live Execution")

    if total_tests == 0:
        st.warning("No standard Python function definitions (`def ...`) detected in source input.")
    else:
        tab1, tab2, tab3 = st.tabs([
            "🧪 Interactive Test Cases", 
            "💻 Executable Pytest Script", 
            "⚡ Fast In-Memory Pytest Runner"
        ])

        full_pytest_script = (
            "# Auto-generated by IBM Bob 2.0 PR Guardian\n"
            "import pytest\n"
            "from solution import *\n\n"
            + "\n\n".join([t["code"] for t in tests])
        )

        with tab1:
            st.caption("Auto-generated edge-case test suite:")
            for idx, t in enumerate(tests):
                with st.expander(f"Case {idx + 1}: {t['name']} ({t['type']})", expanded=True):
                    st.write(f"**Why this test is necessary:** {t['explanation']}")
                    st.code(t["code"], language="python")

        with tab2:
            st.code(full_pytest_script, language="python")
            st.download_button(
                label="📥 Download test_suite.py",
                data=full_pytest_script,
                file_name="test_suite.py",
                mime="text/x-python"
            )

        with tab3:
            st.caption("Executes unit tests live in-memory using dynamic module compilation (zero disk I/O latency).")
            if st.button("🚀 Run Pytest Live Now (In-Memory)", type="secondary"):
                with st.spinner("Compiling modules and running pytest in-memory..."):
                    try:
                        # 1. Dynamically load source code into sys.modules as 'solution'
                        solution_mod = types.ModuleType("solution")
                        exec(source_code, solution_mod.__dict__)
                        sys.modules["solution"] = solution_mod

                        # 2. Dynamically load generated tests into sys.modules as 'test_suite'
                        test_mod = types.ModuleType("test_suite")
                        exec(full_pytest_script, test_mod.__dict__)
                        sys.modules["test_suite"] = test_mod

                        # 3. Capture pytest terminal output directly
                        stdout_capture = io.StringIO()
                        sys.stdout = stdout_capture

                        # Run pytest directly against the in-memory module
                        exit_code = pytest.main(["-q", "--no-header"])

                        sys.stdout = sys.__stdout__  # Restore stdout
                        output_log = stdout_capture.getvalue()

                        if exit_code == 0:
                            st.success("✅ ALL TESTS PASSED SUCCESSFULLY!")
                        else:
                            st.error("❌ TEST SUITE FAILED OR RAISED EXCEPTIONS")

                        st.code(output_log if output_log.strip() else "Pytest execution complete.", language="bash")

                    except Exception as ex:
                        sys.stdout = sys.__stdout__
                        st.error(f"In-Memory Execution Error: {ex}")


# --- SIDEBAR: DOCUMENT CONTEXT INGESTION ---
st.sidebar.header("1. Document Understanding Context")
uploaded_doc = st.sidebar.file_uploader("Upload Specs / Requirement Docs (.md, .txt)", type=["md", "txt"])

doc_text = None
if uploaded_doc:
    doc_text = parse_uploaded_file(uploaded_doc.getvalue())
    st.sidebar.success("Architecture Spec Ingested into IBM Bob 2.0 Engine!")

# --- MAIN INPUT AREA ---
st.header("2. Input Target Python Code")
source_code = st.text_area(
    "Paste Source Code or Method to Generate Tests For:",
    height=220,
    value="""def process_user_reward(total_reward: float, num_users: int) -> list[float]:
    if num_users <= 0:
        raise ValueError("Users count must be greater than zero")
    
    share = total_reward / num_users
    return [share] * num_users"""
)

# --- EXECUTION TRIGGER ---
if st.button("🚀 Trigger IBM Bob 2.0 Multi-Agent Pipeline", type="primary"):
    if not source_code.strip():
        st.error("Please enter valid Python code to perform analysis.")
    else:
        with st.status("IBM Bob 2.0 Subagents Executing...", expanded=True) as status:
            st.write("🤖 **Subagent 1 (AST & Complexity):** Checking single-pass AST depth & security...")
            st.write("⚡ **Subagent 2 (Boundary Synthesizer):** Inferring null safety & zero limits...")
            st.write("📚 **Subagent 3 (Doc Sync Engine):** Verifying spec contracts...")

            results = run_bbob_analysis(source_code, doc_text)
            status.update(label="Subagent Analysis & Test Generation Complete!", state="complete", expanded=False)

        st.divider()
        render_results_section(results, source_code)